Update telegram-notify.yml

diff --git a/.github/workflows/telegram-notify.yml b/.github/workflows/telegram-notify.yml
--- a/.github/workflows/telegram-notify.yml
+++ b/.github/workflows/telegram-notify.yml
@@ -78,9 +78,8 @@ jobs:
         if: steps.time_check.outputs.should_run == 'true'
         env:
           TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
-          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
         run: |
-          # 构建消息内容
           message="Latest commit: ${{ steps.get_commit.outputs.commit }}
           
           File URL: ${{ steps.get_file.outputs.file_url }}
@@ -88,24 +87,25 @@ jobs:
           Content:
           ${{ steps.get_file.outputs.content }}"
           
-          echo "Debug: Sending message: $message"
-          
-          # 使用 curl 发送消息到 Telegram
-          response=$(curl -s -X POST \
-            "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
-            -d "chat_id=$TELEGRAM_CHAT_ID" \
-            -d "text=$message" \
-            -d "parse_mode=HTML" \
-            -w "\n%{http_code}")
-          
-          http_code=$(echo "$response" | tail -n1)
-          content=$(echo "$response" | sed '$d')
-          
-          echo "Debug: HTTP Status Code: $http_code"
-          echo "Debug: Response: $content"
-          
-          if [ "$http_code" != "200" ]; then
-            echo "Error sending message to Telegram"
-            echo "Response: $content"
-            exit 1
-          fi
+          IFS=',' read -r -a ids <<< "$TELEGRAM_CHAT_IDS"  # 将字符串分割成数组
+          for id in "${ids[@]}"; do
+              echo "Debug: Sending message to chat ID: $id"
+              response=$(curl -s -X POST \
+                "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
+                -d "chat_id=$id" \
+                -d "text=$message" \
+                -d "parse_mode=HTML"
+                -w "\n%{http_code}")
+            
+              http_code=$(echo "$response" | tail -n1)
+              content=$(echo "$response" | sed '$d')
+            
+              echo "Debug: HTTP Status Code: $http_code"
+              echo "Debug: Response: $content"
+            
+              if [ "$http_code" != "200" ]; then
+                echo "Error sending message to Telegram"
+                echo "Response: $content"
+                exit 1
+              fi
+          done
